Removed excess dependencies
conda-forge/onnx-feedstock pull request #89
Opened 2023-04-27 16:55 UTC by ilya-lavrenov

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2023-04-27 19:37 UTC, xhochy requested changes
Don't remove Python cross-compiling.

2023-06-03 12:29 UTC, ilya-lavrenov commented
@conda-forge-admin, please rerender

2023-06-03 12:42 UTC, ilya-lavrenov commented
@conda-forge-admin, please rerender

2023-06-03 12:55 UTC, ilya-lavrenov commented
@conda-forge-admin, please rerender

2023-06-06 09:36 UTC, xhochy commented on recipe/meta.yaml
> +    - pytest-runner
What's the reason for this dependency?

2023-09-19 20:26 UTC, closed without merging